### ISSUE TITLE
Error : Test execution fails on windows

### ISSUE THREAD

**Issue by venkateshellaboina** [yury-sannikov/mocha-aura#3]
C:\Test-aura\Aura>npm test

> Aura@1.0.3 pretest C:\Test-aura\Aura
> rollup -c && rollup -c rollup-hooks.config.js

> Aura@1.0.3 test C:\Test-aura\Aura
> mocha

  Hooks
    isAuraFile
      1) should return true for aura controller
      2) should return true for aura helper
      3) should return true for aura renderer
      √ should return false for aura non-js helper
      √ should return false for aura non-js controller
      √ should return false for non aura js file
      √ should return false for non aura js file
      √ should return false for misplaced aura helper
      under windows
        √ should return true for aura helper
        √ should return false for aura non-js helper
      custom regex passed through process.env.AURA_HOOK_REGEX
        √ should return true for custom helper
        √ should return true for custom controller
    auraCodeTransformer
      √ should add module.exports= to the code
    hookIstanbul
      √ should set up hookRequire
      √ hookRequire call should call original hook
    hookRequire
      √ should hook js module extension
    runUnderIstanbul
      4) should be truthy with istanbul in a cache
      √ should be truthy with istanbul in a cache for Windows
      √ should be false with no istanbul in a cache

  15 passing (73ms)
  4 failing

  1) Hooks isAuraFile should return true for aura controller:
     AssertionError: expected false to be truthy
      at Context.<anonymous> (C:/Test-aura/Aura/test/hooksSpec.js:12:7)

  2) Hooks isAuraFile should return true for aura helper:
     AssertionError: expected false to be truthy
      at Context.<anonymous> (C:/Test-aura/Aura/test/hooksSpec.js:15:7)

  3) Hooks isAuraFile should return true for aura renderer:
     AssertionError: expected false to be truthy
      at Context.<anonymous> (C:/Test-aura/Aura/test/hooksSpec.js:40:7)

  4) Hooks runUnderIstanbul should be truthy with istanbul in a cache:
     AssertionError: expected false to be truthy
      at Context.<anonymous> (C:/Test-aura/Aura/test/hooksSpec.js:97:7)

**Comment by yury-sannikov** [comment]
Sorry, I no longer support it since I no longer doing any SF development. (It was worse development experience ever).
SF eventually came up with https://github.com/forcedotcom/LightningTestingService you probably need to look into it.
